### PR TITLE
Add default config if no .ini found

### LINKED ISSUE #30: Games can't be launched if the have no config
If a game doesn't have a config, the config parsing fails and the game is set to be unplayable. This should not be the case and we should default to the old parsing, looking for files in the game subdir.

### PR DESCRIPTION
**Pull request by Loxtir**
Fixes #30

### CODE REVIEW

**Comment by MrEliptik** [comment]
I'm not sure the desired behavior is to create a default config if it's not found. Right now, it's still possible to parse the games without a config so users could be confused seeing a config file created automatically. It might make sense if we decide to force the use of configs. 

In the meantime I think it's safe to just have default values internally

**Comment by Loxtir** [comment]
But that's what this does, adds the default settings like playable and relaunch on crash to a game's dictionary entry if there is no config file in its directory.

**Comment by MrEliptik** [comment]
You're right I'm stupid! I thought it created an .ini automatically

**Review by MrEliptik — COMMENTED** [review]
Thanks for your contribution!

**Pull request merged**
